### PR TITLE
flag for deletion endpoint

### PR DESCRIPTION
**Pull request by rotsee**
This PR adds an endpoint for flagging trees for moderation (currently deleting only):

`POST /flag/delete/12345` will flag tree 12345 for deletion.

The flag can be un-set by explictly adding the wanted value to the request body:

`{"flag": ["false"|"true"]}`

The test database has been updates accordingly, so this can now be tested at https://fruktkartan-api-dev.herokuapp.com/

*This PR _also_ migrates from the dormant Restify framework to Fastify, so I'd like to spend a few days testing it before deploying to prod. *

### CODE REVIEW

**Comment by rotsee** [comment]
(The tests fail because the prod database is not yet updated with the flags col)

**Comment by rotsee** [comment]
Still an open question:

Should flags be stored in a separate table, or shuold we add columns to trees?

Pros with separate table: Clean, flexible (easy to add flag types), can follow the same structure as tree edits, with timestamp, user id, etc
Pros with using the tree table: Makes it easier to filter out flagged trees (to avoid showing trees flagged for deletion, etc)

**Comment by quite** [comment]
Hm, I'm thinking a separate table is better. No, not thinking so much, more feeling :)

**Comment by quite** [comment]
But not really any strong feeling on where to put the delete flag. In the tree table is fine..

**Comment by rotsee** [comment]
> Hm, I'm thinking a separate table is better. No, not thinking so much, more feeling :)

Don't underestimate your gut-feeling! And yes, that's probably the right way to do it.

**Pull request merged**
